export const resourceDefinitions = {
  clients: {
    resource: "clients",
    title: "Clientes",
    description: "Cadastro de clientes por tenant, com perfil e documento.",
    filters: [{ name: "search", label: "Buscar cliente", placeholder: "Nome, documento ou razao social" }],
    columns: [
      { key: "name", label: "Nome" },
      { key: "document", label: "Documento" },
      { key: "profile_type", label: "Perfil" },
      { key: "is_active", label: "Status", render: (value) => <span className="badge">{value ? "Ativo" : "Inativo"}</span> },
    ],
    fields: [
      { name: "name", label: "Nome" },
      { name: "legal_name", label: "Razao social" },
      { name: "document", label: "Documento" },
      {
        name: "profile_type",
        label: "Tipo de perfil",
        type: "select",
        options: [
          { value: "producer", label: "Produtor" },
          { value: "cooperative", label: "Cooperativa" },
          { value: "trader", label: "Trader" },
          { value: "industry", label: "Industria" },
        ],
      },
    ],
  },
  groups: {
    resource: "groups",
    title: "Grupos Economicos",
    description: "Estrutura de grupo para consolidacao de exposicao comercial.",
    filters: [{ name: "search", label: "Buscar grupo", placeholder: "Codigo ou nome" }],
    columns: [
      { key: "code", label: "Codigo" },
      { key: "name", label: "Nome" },
      { key: "client", label: "Cliente" },
    ],
    fields: [
      { name: "client", label: "Cliente ID", type: "number" },
      { name: "code", label: "Codigo" },
      { name: "name", label: "Nome" },
    ],
  },
  subgroups: {
    resource: "subgroups",
    title: "Subgrupos",
    description: "Detalhamento operacional abaixo do grupo economico.",
    filters: [{ name: "search", label: "Buscar subgrupo", placeholder: "Codigo ou nome" }],
    columns: [
      { key: "code", label: "Codigo" },
      { key: "name", label: "Nome" },
      { key: "group", label: "Grupo" },
    ],
    fields: [
      { name: "group", label: "Grupo ID", type: "number" },
      { name: "code", label: "Codigo" },
      { name: "name", label: "Nome" },
    ],
  },
  seasons: {
    resource: "seasons",
    title: "Safras",
    description: "Planejamento de cultivo por cliente e cultura.",
    filters: [{ name: "search", label: "Buscar safra", placeholder: "Ex.: 2025/26" }],
    columns: [
      { key: "season_label", label: "Safra" },
      { key: "client", label: "Cliente" },
      { key: "crop", label: "Cultura" },
      { key: "start_date", label: "Inicio" },
    ],
    fields: [
      { name: "client", label: "Cliente ID", type: "number" },
      { name: "crop", label: "Cultura ID", type: "number" },
      { name: "season_label", label: "Safra" },
      { name: "start_date", label: "Data inicial", type: "date" },
      { name: "end_date", label: "Data final", type: "date" },
    ],
  },
  physicalSales: {
    resource: "physical-sales",
    title: "Vendas Fisicas",
    description: "Operacoes fisicas com contraparte, preco, basis e valor bruto.",
    filters: [{ name: "status", label: "Status", placeholder: "open, partial..." }],
    columns: [
      { key: "trade_date", label: "Trade date" },
      { key: "client", label: "Cliente" },
      { key: "quantity", label: "Quantidade" },
      { key: "price", label: "Preco" },
      { key: "status", label: "Status", render: (value) => <span className="badge">{value}</span> },
    ],
    fields: [
      { name: "client", label: "Cliente ID", type: "number" },
      { name: "group", label: "Grupo ID", type: "number" },
      { name: "subgroup", label: "Subgrupo ID", type: "number" },
      { name: "crop", label: "Cultura ID", type: "number" },
      { name: "season", label: "Safra ID", type: "number" },
      { name: "counterparty", label: "Contraparte ID", type: "number" },
      { name: "unit", label: "Unidade ID", type: "number" },
      { name: "trade_date", label: "Data trade", type: "date" },
      { name: "delivery_start", label: "Entrega inicio", type: "date" },
      { name: "delivery_end", label: "Entrega fim", type: "date" },
      { name: "quantity", label: "Quantidade", type: "number" },
      { name: "price", label: "Preco", type: "number" },
      { name: "currency", label: "Moeda" },
      { name: "status", label: "Status" },
      { name: "notes", label: "Observacoes", type: "textarea" },
    ],
  },
  derivativeOperations: {
    resource: "derivative-operations",
    title: "Operacoes com Derivativos",
    description: "Livro de hedge e derivativos para protecao, especulacao ou estrategias.",
    filters: [{ name: "status", label: "Status", placeholder: "open, partial..." }],
    columns: [
      { key: "trade_date", label: "Trade date" },
      { key: "strategy_name", label: "Estrategia" },
      { key: "market", label: "Mercado" },
      { key: "purpose", label: "Finalidade" },
      { key: "status", label: "Status", render: (value) => <span className="badge">{value}</span> },
    ],
    fields: [
      { name: "client", label: "Cliente ID", type: "number" },
      { name: "group", label: "Grupo ID", type: "number" },
      { name: "subgroup", label: "Subgrupo ID", type: "number" },
      { name: "crop", label: "Cultura ID", type: "number" },
      { name: "season", label: "Safra ID", type: "number" },
      { name: "broker", label: "Broker ID", type: "number" },
      { name: "counterparty", label: "Contraparte ID", type: "number" },
      { name: "trade_date", label: "Data trade", type: "date" },
      { name: "expiry_date", label: "Vencimento", type: "date" },
      { name: "settlement_date", label: "Liquidacao", type: "date" },
      { name: "strategy_name", label: "Nome da estrategia" },
      { name: "market", label: "Mercado" },
      { name: "purpose", label: "Finalidade" },
      { name: "status", label: "Status" },
      { name: "notes", label: "Observacoes", type: "textarea" },
    ],
  },
  derivativeLegs: {
    resource: "derivative-legs",
    title: "Legs de Derivativos",
    description: "Estrutura por perna para futuros, opcoes e swaps.",
    filters: [{ name: "leg_type", label: "Tipo", placeholder: "future, call, put..." }],
    columns: [
      { key: "operation", label: "Operacao" },
      { key: "instrument", label: "Instrumento" },
      { key: "side", label: "Lado" },
      { key: "leg_type", label: "Tipo" },
      { key: "quantity", label: "Quantidade" },
    ],
    fields: [
      { name: "operation", label: "Operacao ID", type: "number" },
      { name: "instrument", label: "Instrumento ID", type: "number" },
      { name: "side", label: "Lado" },
      { name: "leg_type", label: "Tipo" },
      { name: "quantity", label: "Quantidade", type: "number" },
      { name: "contract_size", label: "Contract size", type: "number" },
      { name: "strike", label: "Strike", type: "number" },
      { name: "premium", label: "Premio", type: "number" },
      { name: "reference_price", label: "Preco de referencia", type: "number" },
    ],
  },
  strategies: {
    resource: "strategies",
    title: "Estrategias",
    description: "Governanca comercial com regras de execucao por cliente, safra e cultura.",
    filters: [{ name: "search", label: "Buscar estrategia", placeholder: "Nome ou descricao" }],
    columns: [
      { key: "name", label: "Nome" },
      { key: "client", label: "Cliente" },
      { key: "crop", label: "Cultura" },
      { key: "is_active", label: "Ativa", render: (value) => <span className="badge">{value ? "Sim" : "Nao"}</span> },
    ],
    fields: [
      { name: "client", label: "Cliente ID", type: "number" },
      { name: "crop", label: "Cultura ID", type: "number" },
      { name: "season", label: "Safra ID", type: "number" },
      { name: "name", label: "Nome" },
      { name: "description", label: "Descricao", type: "textarea" },
    ],
  },
  triggers: {
    resource: "strategy-triggers",
    title: "Gatilhos",
    description: "Condicoes operacionais para alertas e disparos.",
    filters: [{ name: "trigger_type", label: "Tipo", placeholder: "price, fx, basis..." }],
    columns: [
      { key: "name", label: "Nome" },
      { key: "strategy", label: "Estrategia" },
      { key: "trigger_type", label: "Tipo" },
      { key: "action_type", label: "Acao" },
    ],
    fields: [
      { name: "strategy", label: "Estrategia ID", type: "number" },
      { name: "name", label: "Nome" },
      { name: "trigger_type", label: "Tipo" },
      { name: "operator", label: "Operador" },
      { name: "target_value", label: "Valor alvo", type: "number" },
      { name: "target_text", label: "Texto alvo" },
      { name: "action_type", label: "Tipo de acao" },
    ],
  },
  market: {
    resource: "market-prices",
    title: "Mercado",
    description: "Serie de precos por instrumento e fonte.",
    filters: [{ name: "price_date", label: "Data", placeholder: "YYYY-MM-DD" }],
    columns: [
      { key: "instrument", label: "Instrumento" },
      { key: "source", label: "Fonte" },
      { key: "price_date", label: "Data" },
      { key: "settlement_price", label: "Settlement" },
    ],
    fields: [
      { name: "instrument", label: "Instrumento ID", type: "number" },
      { name: "source", label: "Fonte ID", type: "number" },
      { name: "price_date", label: "Data", type: "date" },
      { name: "settlement_price", label: "Settlement", type: "number" },
      { name: "close_price", label: "Close", type: "number" },
      { name: "volume", label: "Volume", type: "number" },
    ],
  },
  mtm: {
    resource: "mtm-snapshots",
    title: "MTM",
    description: "Snapshots diarios de mark-to-market das operacoes.",
    filters: [{ name: "snapshot_date", label: "Data", placeholder: "YYYY-MM-DD" }],
    columns: [
      { key: "derivative_operation", label: "Operacao" },
      { key: "snapshot_date", label: "Data" },
      { key: "gross_mtm", label: "Bruto" },
      { key: "net_mtm", label: "Liquido" },
      { key: "currency", label: "Moeda" },
    ],
    fields: [
      { name: "derivative_operation", label: "Operacao ID", type: "number" },
      { name: "snapshot_date", label: "Data", type: "date" },
      { name: "gross_mtm", label: "Gross MTM", type: "number" },
      { name: "premium_effect", label: "Efeito premio", type: "number" },
      { name: "net_mtm", label: "Net MTM", type: "number" },
      { name: "currency", label: "Moeda" },
    ],
  },
  auditing: {
    resource: "audit-logs",
    title: "Auditoria",
    description: "Trilha de auditoria para rastreabilidade de alteracoes.",
    filters: [{ name: "action", label: "Acao", placeholder: "create, update..." }],
    columns: [
      { key: "action", label: "Acao" },
      { key: "user", label: "Usuario" },
      { key: "content_type", label: "Tipo" },
      { key: "created_at", label: "Data" },
    ],
    fields: [
      { name: "user", label: "Usuario ID", type: "number" },
      { name: "content_type", label: "ContentType ID", type: "number" },
      { name: "object_id", label: "Objeto ID", type: "number" },
      { name: "action", label: "Acao" },
      { name: "description", label: "Descricao", type: "textarea" },
    ],
  },
};
