import { moduleOptions } from "../constants/accessModules";

const yesNoOptions = [
  { value: "true", label: "Sim" },
  { value: "false", label: "Nao" },
];

const accessStatusOptions = [
  { value: "pending", label: "Pendente" },
  { value: "active", label: "Ativo" },
];

const userRoleOptions = [
  { value: "owner", label: "Owner" },
  { value: "manager", label: "Manager" },
  { value: "staff", label: "Staff" },
  { value: "viewer", label: "Viewer" },
];

const buySellOptions = [
  { value: "Compra", label: "Compra" },
  { value: "Venda", label: "Venda" },
];

const objetivoVendaDolarizadaOptions = [
  { value: "Venda de componentes", label: "Venda de componentes" },
  { value: "Casamento com divida dolarizada", label: "Casamento com divida dolarizada" },
];

const pfPafOptions = [
  { value: "PF", label: "PF" },
  { value: "PAF", label: "PAF" },
];

const cifFobOptions = [
  { value: "CIF", label: "CIF" },
  { value: "FOB", label: "FOB" },
];

const physicalPaymentClassificationOptions = [
  { value: "Arrendamento", label: "Arrendamento" },
  { value: "Barter", label: "Barter" },
  { value: "Divida de Terras", label: "Divida de Terras" },
  { value: "Outros", label: "Outros" },
];

const moedaCmdtyeOptions = [
  { value: "Moeda", label: "Moeda" },
  { value: "Cmdtye", label: "Cmdtye" },
];

const commonRelationFields = {
  grupo: { type: "relation", resource: "groups", labelKey: "grupo" },
  subgrupo: { type: "relation", resource: "subgroups", labelKey: "subgrupo" },
  cultura: { type: "relation", resource: "crops", labelKey: "ativo" },
  safra: { type: "relation", resource: "seasons", labelKey: "safra" },
  contraparte: { type: "relation", resource: "counterparties", labelKey: "contraparte" },
};

const catalogSelectFields = {
  moeda: { type: "select", resource: "currencies", labelKey: "nome", valueKey: "nome" },
  unidade: { type: "select", resource: "units", labelKey: "nome", valueKey: "nome" },
  moedaUnidade: { type: "select", resource: "price-units", labelKey: "nome", valueKey: "nome" },
  bolsa: { type: "select", resource: "exchanges", labelKey: "nome", valueKey: "nome" },
};

const STANDARD_FIELD_SEQUENCE = ["grupo", "grupos", "subgrupo", "subgrupos", "cultura", "fazer_frente_com", "safra"];

const orderDefinitionEntries = (entries = [], keyName) => {
  const weightFor = (entry) => {
    const key = entry?.[keyName];
    const index = STANDARD_FIELD_SEQUENCE.indexOf(key);
    return index === -1 ? STANDARD_FIELD_SEQUENCE.length : index;
  };

  return [...entries].sort((left, right) => {
    const leftWeight = weightFor(left);
    const rightWeight = weightFor(right);
    if (leftWeight !== rightWeight) {
      return leftWeight - rightWeight;
    }
    return 0;
  });
};

const baseResourceDefinitions = {
  tenants: {
    resource: "tenants",
    title: "Tenants",
    description: "Configuracao do tenant com modulos habilitados.",
    searchPlaceholder: "Buscar tenant...",
    columns: [
      { key: "name", label: "Nome" },
      { key: "slug", label: "Slug" },
      { key: "requires_master_user", label: "Necessita de carteira" },
      { key: "can_send_invitations", label: "Direito a convites" },
      { key: "can_register_groups", label: "Cadastro de grupos" },
      { key: "can_register_subgroups", label: "Cadastro de subgrupos" },
      { key: "enabled_modules", label: "Modulos habilitados", type: "select-multi" },
    ],
    fields: [
      { name: "name", label: "Nome" },
      { name: "slug", label: "Slug" },
      { name: "requires_master_user", label: "Necessita de carteira?", type: "select", options: yesNoOptions, optional: true },
      { name: "can_send_invitations", label: "Terá direito a convites?", type: "select", options: yesNoOptions, optional: true },
      { name: "can_register_groups", label: "Fará cadastro de grupos?", type: "select", options: yesNoOptions, optional: true },
      { name: "can_register_subgroups", label: "Fará cadastro de subgrupos?", type: "select", options: yesNoOptions, optional: true },
      {
        name: "enabled_modules",
        label: "Modulos habilitados",
        type: "select-multi",
        options: moduleOptions,
        optional: true,
        helpText: 'Deixe vazio para "habilitar tudo".',
      },
    ],
  },
  groups: {
    resource: "groups",
    title: "Grupo",
    description: "Cadastro base dos grupos que substituem o antigo datatype de cliente.",
    searchPlaceholder: "Buscar grupo...",
    requestAccessLabel: "Solicitar acesso a um grupo",
    requestAccessTitle: "Solicitar acesso a grupos",
    requestAccessPlaceholder: "Nome do grupo",
    columns: [
      { key: "grupo", label: "Grupo" },
      { key: "owner_name", label: "Proprietario" },
      { key: "users_with_access_names", label: "Usuarios com acesso", type: "select-multi" },
    ],
    fields: [
      { name: "grupo", label: "Grupo" },
      { name: "owner", label: "Proprietario do grupo", type: "relation", resource: "users", labelKey: "full_name" },
      {
        name: "users_with_access",
        label: "Usuarios com acesso",
        type: "multirelation",
        resource: "users",
        labelKey: "full_name",
        optional: true,
        accessManager: true,
        hideSearchInput: true,
        accessManagerShowAllOptions: true,
        accessManagerNotFoundText: "",
      },
    ],
  },
  subgroups: {
    resource: "subgroups",
    title: "Subgrupo",
    description: "Cadastro base dos subgrupos do sistema.",
    searchPlaceholder: "Buscar subgrupo...",
    requestAccessLabel: "Solicitar acesso a um subgrupo",
    requestAccessTitle: "Solicitar acesso a subgrupos",
    requestAccessPlaceholder: "Nome do subgrupo",
    columns: [
      { key: "subgrupo", label: "Subgrupo" },
      { key: "descricao", label: "Descricao" },
      { key: "owner_name", label: "Proprietario" },
      { key: "users_with_access_names", label: "Usuarios com acesso", type: "select-multi" },
    ],
    fields: [
      { name: "subgrupo", label: "Subgrupo" },
      { name: "descricao", label: "Descricao", type: "textarea", optional: true },
      { name: "owner", label: "Proprietario do subgrupo", type: "relation", resource: "users", labelKey: "full_name" },
      {
        name: "users_with_access",
        label: "Usuarios com acesso",
        type: "multirelation",
        resource: "users",
        labelKey: "full_name",
        optional: true,
        accessManager: true,
        hideSearchInput: true,
        accessManagerShowAllOptions: true,
        accessManagerNotFoundText: "",
      },
    ],
  },
  crops: {
    resource: "crops",
    title: "Ativo",
    description: "Ativos base do sistema.",
    searchPlaceholder: "Buscar ativo...",
    columns: [
      { key: "ativo", label: "Ativo" },
      { key: "bolsa_ref", label: "Bolsa de ref", type: "select-multi" },
      { key: "unidade_fisico", label: "Unidade fisico", type: "multirelation", resource: "units", labelKey: "nome" },
      { key: "id", label: "ID" },
    ],
    fields: [
      { name: "ativo", label: "Ativo" },
      {
        name: "bolsa_ref",
        label: "Bolsa de ref",
        type: "select-multi",
        resource: "exchanges",
        labelKey: "nome",
        valueKey: "nome",
      },
      { name: "imagem", label: "Imagem", type: "file", accept: "image/*" },
      { name: "unidade_fisico", label: "Unidade fisico", type: "multirelation", resource: "units", labelKey: "nome", optional: true },
    ],
  },
  currencies: {
    resource: "currencies",
    title: "Moeda",
    description: "Cadastro base de moedas usadas nos formularios.",
    searchPlaceholder: "Buscar moeda...",
    columns: [{ key: "nome", label: "Moeda" }],
    fields: [{ name: "nome", label: "Moeda" }],
  },
  units: {
    resource: "units",
    title: "Unidade",
    description: "Cadastro base de unidades usadas nos formularios.",
    searchPlaceholder: "Buscar unidade...",
    columns: [{ key: "nome", label: "Unidade" }],
    fields: [{ name: "nome", label: "Unidade" }],
  },
  priceUnits: {
    resource: "price-units",
    title: "Moeda/Unidade",
    description: "Cadastro base de combinacoes de moeda por unidade.",
    searchPlaceholder: "Buscar moeda/unidade...",
    columns: [{ key: "nome", label: "Moeda/Unidade" }],
    fields: [
      { name: "nome", label: "Moeda/Unidade", type: "price-unit-builder", resources: ["currencies", "units"] },
    ],
  },
  exchanges: {
    resource: "exchanges",
    title: "Bolsa",
    description: "Cadastro base de bolsas usadas nos formularios.",
    searchPlaceholder: "Buscar bolsa...",
    columns: [
      { key: "nome", label: "Bolsa" },
      { key: "ativo", label: "Ativo" },
      { key: "moeda_bolsa", label: "Moeda da bolsa" },
      { key: "volume_padrao_contrato", label: "Volume padrao do contrato", type: "number" },
      { key: "unidade_bolsa", label: "Unidade da bolsa" },
      { key: "moeda_cmdtye", label: "Moeda/Cmdtye" },
      { key: "moeda_unidade_padrao", label: "Moeda/Unidade padrao" },
      { key: "fator_conversao_unidade_padrao_cultura", label: "Fator conversao unid. padrao", type: "number" },
    ],
    fields: [
      { name: "nome", label: "Bolsa" },
      { name: "ativo", label: "Ativo", type: "select", resource: "crops", labelKey: "ativo", valueKey: "ativo" },
      { name: "moeda_bolsa", label: "Moeda da bolsa", ...catalogSelectFields.moeda },
      { name: "volume_padrao_contrato", label: "Volume padrao do contrato", type: "number" },
      { name: "unidade_bolsa", label: "Unidade da bolsa", ...catalogSelectFields.unidade },
      { name: "moeda_cmdtye", label: "Moeda/Cmdtye", type: "select", options: moedaCmdtyeOptions },
      { name: "moeda_unidade_padrao", label: "Moeda/Unidade padrao", ...catalogSelectFields.moedaUnidade },
      { name: "fator_conversao_unidade_padrao_cultura", label: "Fator de conversao para unidade padrao da cultura", type: "number" },
    ],
  },
  derivativeOperationNames: {
    resource: "derivative-operation-names",
    title: "Nome Operacoes Derivativos",
    description: "Cadastro base dos nomes de operacoes de derivativos.",
    searchPlaceholder: "Buscar nome da operacao...",
    columns: [{ key: "nome", label: "Nome da operacao" }],
    fields: [{ name: "nome", label: "Nome da operacao" }],
  },
  seasons: {
    resource: "seasons",
    title: "Safra",
    description: "Safras base do sistema, no mesmo estilo simples da cultura.",
    searchPlaceholder: "Buscar safra...",
    columns: [
      { key: "safra", label: "Safra" },
      { key: "id", label: "ID" },
    ],
    fields: [{ name: "safra", label: "Safra" }],
  },
  counterparties: {
    resource: "counterparties",
    title: "Contrapartes",
    description: "Contrapartes ligadas a grupo e subgrupo.",
    searchPlaceholder: "Buscar contraparte...",
    columns: [
      { key: "contraparte", label: "Contraparte" },
      { key: "grupo", label: "Grupo", type: "relation", ...commonRelationFields.grupo },
      { key: "subgrupo", label: "Subgrupo", type: "relation", ...commonRelationFields.subgrupo },
      { key: "obs", label: "Observacoes" },
    ],
    fields: [
      { name: "contraparte", label: "Contraparte" },
      { name: "grupo", label: "Grupo", ...commonRelationFields.grupo, optional: true },
      { name: "subgrupo", label: "Subgrupo", ...commonRelationFields.subgrupo, optional: true },
      { name: "obs", label: "Observacoes", type: "textarea" },
    ],
  },
  physicalQuotes: {
    resource: "physical-quotes",
    title: "Cotacoes Fisico",
    description: "Cotacoes fisicas com moeda/unidade, data de pagamento e report.",
    searchPlaceholder: "Buscar cotacao, cultura ou localidade...",
    columns: [
      { key: "cultura_texto", label: "Ativo" },
      { key: "cotacao", label: "Cotacao", type: "number" },
      { key: "moeda_unidade", label: "Moeda/Unidade" },
      { key: "data_report", label: "Data report", type: "date" },
      { key: "localidade", label: "Localidade" },
    ],
    fields: [
      { name: "cotacao", label: "Cotacao", type: "number" },
      { name: "cultura_texto", label: "Ativo", type: "select", resource: "crops", labelKey: "ativo", valueKey: "ativo" },
      { name: "data_pgto", label: "Data pgto", type: "date" },
      { name: "data_report", label: "Data report", type: "date" },
      {
        name: "localidade",
        label: "Localidade",
        type: "select",
        resource: "crop-boards",
        listField: "localidade",
        dedupeByValue: true,
      },
      { name: "moeda_unidade", label: "Moeda/Unidade", ...catalogSelectFields.moedaUnidade },
      { name: "safra", label: "Safra", ...commonRelationFields.safra, optional: true },
      { name: "obs", label: "Observacoes", type: "textarea" },
    ],
  },
  tradingviewWatchlistQuotes: {
    resource: "tradingview-watchlist-quotes",
    title: "Cotacoes",
    description: "",
    searchPlaceholder: "Buscar simbolo, secao ou descricao...",
    readonly: true,
    allowCreate: false,
    allowDelete: false,
    allowDuplicate: false,
    disableReadonlyDetails: true,
    showClearButton: false,
    autoRefreshIntervalMs: 60000,
    columns: [
      { key: "section_name", label: "Secao" },
      { key: "ticker", label: "Ticker" },
      { key: "description", label: "Descricao" },
      { key: "price", label: "Preco", type: "number" },
      { key: "change_percent", label: "Variacao %", type: "number" },
      { key: "change_value", label: "Variacao", type: "number" },
      { key: "currency", label: "Moeda" },
      { key: "instrument_type", label: "Tipo" },
      { key: "id", label: "ID" },
      { key: "symbol", label: "Simbolo" },
    ],
    fields: [],
  },
  marketNewsPosts: {
    resource: "market-news-posts",
    title: "Blog/News",
    description: "",
    searchPlaceholder: "Buscar titulo ou categoria...",
    columns: [
      { key: "data_publicacao", label: "Data publicacao", type: "date" },
      { key: "titulo", label: "Titulo" },
      { key: "categorias", label: "Categorias", type: "select-multi" },
      { key: "status_artigo", label: "Status do artigo" },
      { key: "published_by_name", label: "Publicado por" },
    ],
    fields: [
      { name: "titulo", label: "Titulo" },
      { name: "data_publicacao", label: "Data publicacao", type: "date", optional: true },
      {
        name: "status_artigo",
        label: "Status do artigo",
        type: "select",
        options: [
          { value: "draft", label: "Rascunho" },
          { value: "published", label: "Publicado" },
        ],
      },
      { name: "categorias", label: "Categorias", type: "json-list", helpText: "Separe as categorias por virgula." },
      {
        name: "conteudo_html",
        label: "Conteudo HTML",
        type: "textarea",
        helpText: "A tela principal do blog usa editor rico continuo com HTML no mesmo fluxo do texto.",
      },
    ],
  },
  budgetCosts: {
    resource: "budget-costs",
    title: "Custo Orcamento",
    description: "Custos orcados por grupo, subgrupo, cultura e safra.",
    searchPlaceholder: "Buscar grupo despesa...",
    columns: [
      { key: "grupo_despesa", label: "Grupo despesa" },
      { key: "grupo", label: "Grupo", type: "relation", ...commonRelationFields.grupo },
      { key: "subgrupo", label: "Subgrupo", type: "relation", ...commonRelationFields.subgrupo },
      { key: "valor", label: "Valor", type: "number" },
      { key: "moeda", label: "Moeda" },
    ],
    fields: [
      { name: "grupo", label: "Grupo", ...commonRelationFields.grupo, optional: true },
      { name: "subgrupo", label: "Subgrupo", ...commonRelationFields.subgrupo, optional: true },
      { name: "cultura", label: "Ativo", ...commonRelationFields.cultura, optional: true },
      { name: "safra", label: "Safra", ...commonRelationFields.safra, optional: true },
      { name: "considerar_na_politica_de_hedge", label: "Considerar na politica de hedge", type: "select", options: yesNoOptions },
      { name: "grupo_despesa", label: "Grupo despesa" },
      { name: "moeda", label: "Moeda", ...catalogSelectFields.moeda },
      { name: "valor", label: "Valor", type: "number" },
      { name: "obs", label: "Observacoes", type: "textarea" },
    ],
  },
  actualCosts: {
    resource: "actual-costs",
    title: "Custo Realizado",
    description: "Custos realizados por grupo, subgrupo, cultura e safra.",
    searchPlaceholder: "Buscar grupo despesa...",
    columns: [
      { key: "grupo_despesa", label: "Grupo despesa" },
      { key: "grupo", label: "Grupo", type: "relation", ...commonRelationFields.grupo },
      { key: "subgrupo", label: "Subgrupo", type: "relation", ...commonRelationFields.subgrupo },
      { key: "valor", label: "Valor", type: "number" },
      { key: "moeda", label: "Moeda" },
    ],
    fields: [
      { name: "grupo", label: "Grupo", ...commonRelationFields.grupo, optional: true },
      { name: "subgrupo", label: "Subgrupo", ...commonRelationFields.subgrupo, optional: true },
      { name: "cultura", label: "Ativo", ...commonRelationFields.cultura, optional: true },
      { name: "safra", label: "Safra", ...commonRelationFields.safra, optional: true },
      {
        name: "grupo_despesa",
        label: "Grupo despesa",
        type: "select",
        resource: "budget-costs",
        labelKey: "grupo_despesa",
        valueKey: "grupo_despesa",
        filterByCurrent: {
          grupo: "grupo",
          subgrupo: "subgrupo",
          cultura: "cultura",
          safra: "safra",
        },
        dedupeByValue: true,
      },
      { name: "moeda", label: "Moeda", ...catalogSelectFields.moeda },
      { name: "valor", label: "Valor", type: "number" },
      { name: "obs", label: "Observacoes", type: "textarea" },
    ],
  },
  derivativeOperations: {
    resource: "derivative-operations",
    title: "Derivativos",
    description: "Operacoes maes de derivativos com filhos vinculados ao mesmo codigo mae.",
    customForm: "derivative-operation",
    attachmentField: { name: "attachments", label: "Anexos", type: "file-multi" },
    searchPlaceholder: "Buscar derivativo...",
    columns: [
      { key: "cod_operacao_mae", label: "Cod operacao mae" },
      { key: "nome_da_operacao", label: "Nome da operacao" },
      { key: "status_operacao", label: "Status" },
      { key: "bolsa_ref", label: "Bolsa" },
      { key: "grupo", label: "Grupo", type: "relation", ...commonRelationFields.grupo },
      { key: "subgrupo", label: "Subgrupo", type: "relation", ...commonRelationFields.subgrupo },
      { key: "data_contratacao", label: "Data contratacao", type: "date" },
      { key: "quantidade_derivativos", label: "Qtd derivativos", type: "number" },
    ],
    fields: [],
  },
  strategies: {
    resource: "strategies",
    title: "Estrategias",
    description: "Estrategias com grupo, subgrupo, status e validade.",
    searchPlaceholder: "Buscar estrategia...",
    columns: [
      { key: "descricao_estrategia", label: "Descricao" },
      { key: "grupo", label: "Grupo", type: "relation", ...commonRelationFields.grupo },
      { key: "subgrupo", label: "Subgrupo", type: "relation", ...commonRelationFields.subgrupo },
      { key: "status", label: "Status" },
      { key: "data_validade", label: "Validade", type: "date" },
    ],
    fields: [
      { name: "data_validade", label: "Data validade", type: "date" },
      { name: "descricao_estrategia", label: "Descricao da estrategia", type: "textarea" },
      { name: "grupo", label: "Grupo", ...commonRelationFields.grupo, optional: true },
      { name: "subgrupo", label: "Subgrupo", ...commonRelationFields.subgrupo, optional: true },
      { name: "obs", label: "Observacoes", type: "textarea" },
      { name: "status", label: "Status" },
    ],
  },
  strategyTriggers: {
    resource: "strategy-triggers",
    title: "Gatilhos",
    description: "Gatilhos relacionados a estrategia, cultura, grupo e subgrupo.",
    searchPlaceholder: "Buscar gatilho...",
    columns: [
      { key: "grupos", label: "Grupo", type: "multirelation", resource: "groups", labelKey: "grupo" },
      { key: "subgrupos", label: "Subgrupo", type: "multirelation", resource: "subgroups", labelKey: "subgrupo" },
      { key: "cultura", label: "Ativo", type: "relation", ...commonRelationFields.cultura },
      { key: "contrato_bolsa", label: "Contrato bolsa" },
      { key: "tipo_fis_der", label: "Tipo" },
      { key: "status_gatilho", label: "Status gatilho" },
      { key: "strike_alvo", label: "Strike alvo", type: "number" },
    ],
    fields: [
      { name: "estrategia", label: "Estrategia", type: "relation", resource: "strategies", labelKey: "descricao_estrategia", optional: true },
      { name: "acima_abaixo", label: "Acima/Abaixo" },
      { name: "contrato_bolsa", label: "Contrato bolsa" },
      { name: "cultura", label: "Ativo", ...commonRelationFields.cultura, optional: true },
      { name: "codigo_derivativo", label: "Codigo derivativo" },
      { name: "codigos_estrategia", label: "Codigos da estrategia", type: "json-list", helpText: "Separe por virgula." },
      { name: "grupos", label: "Grupo", type: "multirelation", resource: "groups", labelKey: "grupo", optional: true },
      { name: "subgrupos", label: "Subgrupo", type: "multirelation", resource: "subgroups", labelKey: "subgrupo", optional: true },
      { name: "posicao", label: "Posicao" },
      { name: "produto_bolsa", label: "Produto/Bolsa" },
      { name: "status_gatilho", label: "Status gatilho" },
      { name: "strike_alvo", label: "Strike alvo", type: "number" },
      { name: "tipo_fis_der", label: "Tipo (Fis/Der)" },
      { name: "unidade", label: "Unidade", ...catalogSelectFields.unidade },
      { name: "volume", label: "Volume", type: "number" },
      { name: "obs", label: "Observacoes", type: "textarea" },
      { name: "status", label: "Status" },
    ],
  },
  hedgePolicies: {
    resource: "hedge-policies",
    title: "Politica de Hedge",
    description: "Politicas de hedge por cultura, grupos, subgrupos e safra.",
    searchPlaceholder: "Buscar politica...",
    columns: [
      { key: "grupos", label: "Grupo", type: "multirelation", resource: "groups", labelKey: "grupo" },
      { key: "subgrupos", label: "Subgrupo", type: "multirelation", resource: "subgroups", labelKey: "subgrupo" },
      { key: "cultura", label: "Ativo", type: "relation", ...commonRelationFields.cultura },
      { key: "safra", label: "Safra", type: "relation", ...commonRelationFields.safra },
      { key: "mes_ano", label: "Mes/Ano", type: "date" },
      { key: "margem_alvo_minimo", label: "Margem alvo minimo", type: "number" },
    ],
    fields: [
      { name: "cultura", label: "Ativo", ...commonRelationFields.cultura, optional: true },
      { name: "grupos", label: "Grupo", type: "multirelation", resource: "groups", labelKey: "grupo", optional: true },
      { name: "subgrupos", label: "Subgrupo", type: "multirelation", resource: "subgroups", labelKey: "subgrupo", optional: true },
      { name: "safra", label: "Safra", ...commonRelationFields.safra, optional: true },
      { name: "insumos_travados_maximo", label: "Insumos travados maximo", type: "number" },
      { name: "insumos_travados_minimo", label: "Insumos travados minimo", type: "number" },
      { name: "margem_alvo_minimo", label: "Margem alvo minimo", type: "number" },
      { name: "mes_ano", label: "Mes/Ano", type: "date" },
      { name: "vendas_x_custo_maximo", label: "Vendas x custo maximo", type: "number" },
      { name: "vendas_x_custo_minimo", label: "Vendas x custo minimo", type: "number" },
      { name: "vendas_x_prod_total_maximo", label: "Vendas x prod total maximo", type: "number" },
      { name: "vendas_x_prod_total_minimo", label: "Vendas x prod total minimo", type: "number" },
      { name: "obs", label: "Observacoes", type: "textarea" },
    ],
  },
  cropBoards: {
    resource: "crop-boards",
    title: "Quadro Safra",
    description: "Quadro de safra com area, produtividade, producao e monitoramento.",
    searchPlaceholder: "Buscar quadro safra...",
    columns: [
      { key: "grupo", label: "Grupo", type: "relation", ...commonRelationFields.grupo },
      { key: "subgrupo", label: "Subgrupo", type: "relation", ...commonRelationFields.subgrupo },
      { key: "cultura", label: "Ativo", type: "relation", ...commonRelationFields.cultura },
      { key: "safra", label: "Safra", type: "relation", ...commonRelationFields.safra },
      { key: "localidade", label: "Locais de producao" },
      { key: "area", label: "Area", type: "number" },
      { key: "producao_total", label: "Producao total", type: "number" },
      { key: "monitorar_vc", label: "Monitorar VC?", type: "boolean" },
    ],
    fields: [
      { name: "cultura", label: "Ativo", ...commonRelationFields.cultura, optional: true },
      { name: "grupo", label: "Grupo", ...commonRelationFields.grupo, optional: true },
      { name: "subgrupo", label: "Subgrupo", ...commonRelationFields.subgrupo, optional: true },
      { name: "safra", label: "Safra", ...commonRelationFields.safra, optional: true },
      { name: "localidade", label: "Locais de producao", type: "localidade-list" },
      { name: "area", label: "Area", type: "number" },
      { name: "bolsa_ref", label: "Bolsa ref", ...catalogSelectFields.bolsa },
      { name: "monitorar_vc", label: "Monitorar VC?", type: "select", options: yesNoOptions },
      { name: "produtividade", label: "Produtividade", type: "number" },
      { name: "producao_total", label: "Producao total", type: "number", readOnly: true },
      { name: "criar_politica_hedge", label: "Criar politica de hedge?", type: "select", options: yesNoOptions },
      { name: "unidade_producao", label: "Unidade producao", ...catalogSelectFields.unidade },
      { name: "obs", label: "Observacoes", type: "textarea" },
    ],
  },
  physicalSales: {
    resource: "physical-sales",
    title: "Vendas Fisico",
    description: "Operacoes de vendas fisicas com basis, bolsa, dolar e faturamento.",
    searchPlaceholder: "Buscar venda fisica...",
    columns: [
      { key: "grupo", label: "Grupo", type: "relation", ...commonRelationFields.grupo },
      { key: "subgrupo", label: "Subgrupo", type: "relation", ...commonRelationFields.subgrupo },
      { key: "cultura_produto", label: "Cultura produto" },
      { key: "localidade", label: "Localidade" },
      { key: "safra", label: "Safra", type: "relation", ...commonRelationFields.safra },
      { key: "bolsa_ref", label: "Bolsa ref" },
      { key: "contrato_bolsa", label: "Contrato bolsa" },
      { key: "compra_venda", label: "Compra/Venda" },
      { key: "preco", label: "Preco", type: "number" },
      { key: "moeda_unidade", label: "Volume fisico moeda" },
      { key: "volume_fisico", label: "Volume fisico volume", type: "number" },
    ],
    fields: [
      { name: "grupo", label: "Grupo", ...commonRelationFields.grupo, optional: true },
      { name: "subgrupo", label: "Subgrupo", ...commonRelationFields.subgrupo, optional: true },
      { name: "safra", label: "Safra", ...commonRelationFields.safra, optional: true },
      {
        name: "localidade",
        label: "Localidade",
        type: "select",
        resource: "crop-boards",
        listField: "localidade",
        dedupeByValue: true,
        optional: true,
      },
      { name: "basis_valor", label: "Basis valor", type: "number" },
      { name: "basis_moeda", label: "Basis moeda", type: "text", readOnly: true },
      {
        name: "bolsa_ref",
        label: "Bolsa ref",
        type: "select",
        resource: "tradingview-watchlist-quotes",
        labelKey: "section_name",
        valueKey: "section_name",
        dedupeByValue: true,
        optional: true,
      },
      {
        name: "contrato_bolsa",
        label: "Contrato bolsa",
        type: "select",
        resource: "tradingview-watchlist-quotes",
        labelKey: "ticker",
        valueKey: "ticker",
        filterByCurrent: {
          section_name: "bolsa_ref",
        },
        optional: true,
      },
      { name: "cif_fob", label: "CIF/FOB", type: "select", options: cifFobOptions },
      { name: "compra_venda", label: "Compra/Venda", type: "select", options: buySellOptions },
      {
        name: "contraparte",
        label: "Contraparte",
        ...commonRelationFields.contraparte,
        optional: true,
        filterByCurrent: {
          grupo: "grupo",
          subgrupo: "subgrupo",
        },
      },
      { name: "cotacao_bolsa_ref", label: "Cotacao bolsa ref", type: "number" },
      {
        name: "cultura_produto",
        label: "Cultura produto",
        type: "select",
        resources: ["crop-boards", "crops"],
        getOptions: ({ lookupOptions }) => {
          const cropBoards = Array.isArray(lookupOptions["crop-boards"]) ? lookupOptions["crop-boards"] : [];
          const crops = Array.isArray(lookupOptions.crops) ? lookupOptions.crops : [];
          const cropMap = new Map(
            crops.map((item) => [
              String(item.id),
              item.ativo || item.cultura || item.nome || item.label || item.descricao || String(item.id),
            ]),
          );
          const values = cropBoards
            .map((item) => {
              if (item?.cultura && typeof item.cultura === "object") {
                return item.cultura.ativo || item.cultura.cultura || item.cultura.nome || item.cultura.label || item.cultura.descricao || "";
              }
              if (item?.cultura != null) {
                return cropMap.get(String(item.cultura)) || "";
              }
              return "";
            })
            .filter(Boolean);

          return [...new Set(values)].map((value) => ({
            value,
            label: value,
          }));
        },
      },
      { name: "data_entrega", label: "Data entrega", type: "date" },
      { name: "data_negociacao", label: "Data negociacao", type: "date" },
      { name: "data_pagamento", label: "Data pagamento", type: "date" },
      { name: "dolar_de_venda", label: "Dolar de venda futuro", type: "number" },
      { name: "faturamento_total_contrato", label: "Faturamento total do contrato", type: "number", readOnly: true },
      { name: "moeda_contrato", label: "Moeda contrato", ...catalogSelectFields.moeda },
      { name: "moeda_unidade", label: "Volume fisico moeda", ...catalogSelectFields.moedaUnidade, optional: true },
      {
        name: "objetivo_venda_dolarizada",
        label: "Objetivo venda dolarizada",
        type: "select",
        options: objetivoVendaDolarizadaOptions,
        visibleWhen: {
          field: "moeda_contrato",
          notEquals: "R$",
        },
      },
      { name: "pf_paf", label: "PF/PAF", type: "select", options: pfPafOptions },
      { name: "preco", label: "Preco", type: "number" },
      { name: "unidade_contrato", label: "Unidade contrato", ...catalogSelectFields.unidade },
      { name: "volume_fisico", label: "Volume fisico volume", type: "number" },
      { name: "obs", label: "Obs", type: "textarea", optional: true },
      { name: "attachments", label: "Anexos", type: "file-multi" },
    ],
  },
  physicalPayments: {
    resource: "physical-payments",
    title: "Pgtos Fisico",
    description: "Pagamentos fisicos com grupo, subgrupo, cultura, safra, volume e contraparte.",
    searchPlaceholder: "Buscar pgto fisico...",
    columns: [
      { key: "grupo", label: "Grupo", type: "relation", ...commonRelationFields.grupo },
      { key: "subgrupo", label: "Subgrupo", type: "relation", ...commonRelationFields.subgrupo },
      { key: "fazer_frente_com", label: "Fazer frente com", type: "relation", ...commonRelationFields.cultura },
      { key: "safra", label: "Safra", type: "relation", ...commonRelationFields.safra },
      { key: "classificacao", label: "Classificacao" },
      { key: "volume", label: "Volume", type: "number" },
      { key: "unidade", label: "Unidade" },
      { key: "data_pagamento", label: "Data pagamento", type: "date" },
      { key: "contraparte", label: "Contraparte", type: "relation", ...commonRelationFields.contraparte },
    ],
    fields: [
      { name: "grupo", label: "Grupo", ...commonRelationFields.grupo, optional: true },
      { name: "subgrupo", label: "Subgrupo", ...commonRelationFields.subgrupo, optional: true },
      { name: "fazer_frente_com", label: "Fazer frente com", ...commonRelationFields.cultura, optional: true },
      { name: "safra", label: "Safra", ...commonRelationFields.safra, optional: true },
      { name: "classificacao", label: "Classificacao", type: "select", options: physicalPaymentClassificationOptions },
      { name: "volume", label: "Volume", type: "number" },
      { name: "unidade", label: "Unidade", ...catalogSelectFields.unidade },
      { name: "data_pagamento", label: "Data pagamento", type: "date" },
      { name: "descricao", label: "Descricao", type: "textarea" },
      { name: "obs", label: "Obs", type: "textarea", optional: true },
      { name: "contraparte", label: "Contraparte", ...commonRelationFields.contraparte, optional: true },
    ],
  },
  cashPayments: {
    resource: "cash-payments",
    title: "Pgtos Caixa",
    description: "Pagamentos de caixa com grupo, subgrupo, valor da parcela, valor total da operacao, moeda e contraparte.",
    searchPlaceholder: "Buscar pgto caixa...",
    columns: [
      { key: "grupo", label: "Grupo", type: "relation", ...commonRelationFields.grupo },
      { key: "subgrupo", label: "Subgrupo", type: "relation", ...commonRelationFields.subgrupo },
      { key: "fazer_frente_com", label: "Fazer frente com", type: "relation", ...commonRelationFields.cultura },
      { key: "safra", label: "Safra", type: "relation", ...commonRelationFields.safra },
      { key: "volume", label: "Valor parcela", type: "number" },
      { key: "volume_total_operacao", label: "Valor total da operacao", type: "number" },
      { key: "moeda", label: "Moeda" },
      { key: "data_desembolso", label: "Data desembolso", type: "date" },
      { key: "data_pagamento", label: "Data pagamento parcela", type: "date" },
      { key: "contraparte", label: "Contraparte", type: "relation", ...commonRelationFields.contraparte },
    ],
    fields: [
      { name: "grupo", label: "Grupo", ...commonRelationFields.grupo, optional: true },
      { name: "subgrupo", label: "Subgrupo", ...commonRelationFields.subgrupo, optional: true },
      { name: "fazer_frente_com", label: "Fazer frente com", ...commonRelationFields.cultura, optional: true },
      { name: "safra", label: "Safra", ...commonRelationFields.safra, optional: true },
      { name: "volume", label: "Valor parcela", type: "number" },
      { name: "volume_total_operacao", label: "Valor total da operacao", type: "number", optional: true },
      { name: "moeda", label: "Moeda", ...catalogSelectFields.moeda },
      { name: "data_desembolso", label: "Data desembolso", type: "date" },
      { name: "data_pagamento", label: "Data pagamento parcela", type: "date" },
      { name: "descricao", label: "Descricao", type: "textarea" },
      { name: "obs", label: "Obs", type: "textarea", optional: true },
      { name: "contraparte", label: "Contraparte", ...commonRelationFields.contraparte, optional: true },
    ],
  },
  logs: {
    resource: "audit-logs",
    title: "Log",
    description: "Registro de criacoes, alteracoes e exclusoes dos formularios.",
    readonly: true,
    allowDelete: true,
    allowCreate: false,
    allowDuplicate: false,
    searchPlaceholder: "Buscar formulario, usuario ou descricao...",
    requireFiltersBeforeLoad: true,
    columns: [
      { key: "formulario", label: "Formulario" },
      { key: "object_id", label: "ID alterado" },
      { key: "usuario", label: "Alterado por" },
      { key: "action", label: "Acao" },
      { key: "description", label: "Descricao" },
      { key: "created_at_display", label: "Data e hora" },
    ],
    fields: [],
    detailFields: [
      { name: "formulario", label: "Formulario" },
      { name: "object_id", label: "ID alterado" },
      { name: "usuario", label: "Alterado por" },
      { name: "action", label: "Acao" },
      { name: "created_at_display", label: "Data e hora" },
      { name: "id", label: "ID do log" },
      { name: "description", label: "Descricao", type: "textarea" },
    ],
  },
  users: {
    resource: "users",
    title: "Usuarios",
    description: "Gestao de usuarios do sistema, incluindo grupos e subgrupos atribuidos.",
    searchPlaceholder: "Buscar usuario, nome ou email...",
    columns: [
      { key: "username", label: "Usuario" },
      { key: "full_name", label: "Nome completo" },
      { key: "email", label: "Email" },
      { key: "tenant_name", label: "Perfil / tenant" },
      { key: "carteira_name", label: "Carteira" },
      { key: "access_status", label: "Status" },
      { key: "is_active", label: "Ativo" },
    ],
    fields: [
      { name: "tenant", label: "Tenant", type: "relation", resource: "tenants", labelKey: "name", optional: true },
      {
        name: "master_user",
        label: "Carteira",
        type: "relation",
        resource: "users",
        labelKey: "full_name",
        optional: true,
        visibleWhen: {
          predicate: (values, lookupOptions) => {
            const tenantId = values.tenant;
            const tenants = lookupOptions?.tenants || [];
            const selectedTenant = tenants.find((item) => String(item.id) === String(tenantId));
            return Boolean(selectedTenant?.requires_master_user);
          },
        },
      },
      { name: "username", label: "Usuario" },
      { name: "full_name", label: "Nome completo" },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Telefone" },
      { name: "password", label: "Senha", type: "password", optional: true, helpText: "Preencha para definir ou alterar a senha do usuario." },
      { name: "access_status", label: "Status", type: "select", options: accessStatusOptions },
    ],
  },
  inviteAccess: {
    resource: "users",
    title: "Convites e acessos",
    description: "Configure quantos convites administrativos cada usuário pode enviar e quantos grupos e subgrupos ele pode possuir.",
    searchPlaceholder: "Buscar usuario por nome, email ou tenant...",
    allowCreate: false,
    allowDelete: false,
    allowDuplicate: false,
    enableRunActions: false,
    columns: [
      { key: "username", label: "Usuario" },
      { key: "full_name", label: "Nome completo" },
      { key: "tenant_name", label: "Tenant" },
      { key: "email", label: "Email" },
      { key: "active_admin_invitations_count", label: "Convites ativos", type: "number" },
      { key: "max_admin_invitations", label: "Limite convites", type: "number" },
      { key: "owned_groups_count", label: "Grupos proprietario", type: "number" },
      { key: "max_owned_groups", label: "Limite grupos", type: "number" },
      { key: "owned_subgroups_count", label: "Subgrupos proprietario", type: "number" },
      { key: "max_owned_subgroups", label: "Limite subgrupos", type: "number" },
    ],
    fields: [
      { name: "tenant", label: "Tenant", type: "relation", resource: "tenants", labelKey: "name", optional: true },
      { name: "username", label: "Usuario" },
      { name: "full_name", label: "Nome completo" },
      { name: "email", label: "Email", type: "email" },
      { name: "max_admin_invitations", label: "Limite de convites administrativos", type: "number", optional: true },
      { name: "max_owned_groups", label: "Limite de grupos como proprietario", type: "number", optional: true },
      { name: "max_owned_subgroups", label: "Limite de subgrupos como proprietario", type: "number", optional: true },
      { name: "access_status", label: "Status", type: "select", options: accessStatusOptions },
    ],
  },
  adminInvitations: {
    resource: "admin-invitations",
    title: "Convites (Admin)",
    description: "Envie convites administrativos e já defina os grupos e subgrupos que o usuário receberá ao aceitar.",
    searchPlaceholder: "Buscar convite por email ou tenant...",
    submitLabel: "Enviar convite",
    columns: [
      { key: "target_tenant_name", label: "Tenant" },
      { key: "email", label: "Email" },
      { key: "assigned_groups", label: "Grupos atribuidos", type: "multirelation", resource: "groups", labelKey: "grupo" },
      { key: "assigned_subgroups", label: "Subgrupos atribuidos", type: "multirelation", resource: "subgroups", labelKey: "subgrupo" },
      { key: "status", label: "Status" },
      { key: "accepted_user_name", label: "Usuario criado" },
      { key: "invite_url", label: "Link do convite" },
    ],
    fields: [
      { name: "target_tenant_slug", label: "Tipo de convite", type: "select", resource: "tenants", labelKey: "name", valueKey: "slug" },
      { name: "email", label: "Email", type: "email" },
      {
        name: "assigned_groups",
        label: "Grupos atribuidos",
        type: "multirelation",
        resource: "groups",
        labelKey: "grupo",
        optional: true,
        accessManager: true,
        hideSearchInput: true,
        accessManagerShowAllOptions: true,
        accessManagerTitle: "Selecione os grupos abaixo",
        accessManagerEmptyText: "Nenhum grupo atribuido.",
        accessManagerNotFoundText: "Nenhum grupo encontrado.",
        accessManagerRemoveTitle: "Remover grupo atribuido",
      },
      {
        name: "assigned_subgroups",
        label: "Subgrupos atribuidos",
        type: "multirelation",
        resource: "subgroups",
        labelKey: "subgrupo",
        optional: true,
        accessManager: true,
        hideSearchInput: true,
        accessManagerShowAllOptions: true,
        accessManagerTitle: "Selecione os subgrupos abaixo",
        accessManagerEmptyText: "Nenhum subgrupo atribuido.",
        accessManagerNotFoundText: "Nenhum subgrupo encontrado.",
        accessManagerRemoveTitle: "Remover subgrupo atribuido",
      },
    ],
    editFields: [
      { name: "target_tenant_slug", label: "Tipo de convite", type: "select", resource: "tenants", labelKey: "name", valueKey: "slug" },
      { name: "email", label: "Email", type: "email" },
      {
        name: "assigned_groups",
        label: "Grupos atribuidos",
        type: "multirelation",
        resource: "groups",
        labelKey: "grupo",
        optional: true,
        accessManager: true,
        hideSearchInput: true,
        accessManagerShowAllOptions: true,
        accessManagerTitle: "Selecione os grupos abaixo",
        accessManagerEmptyText: "Nenhum grupo atribuido.",
        accessManagerNotFoundText: "Nenhum grupo encontrado.",
        accessManagerRemoveTitle: "Remover grupo atribuido",
      },
      {
        name: "assigned_subgroups",
        label: "Subgrupos atribuidos",
        type: "multirelation",
        resource: "subgroups",
        labelKey: "subgrupo",
        optional: true,
        accessManager: true,
        hideSearchInput: true,
        accessManagerShowAllOptions: true,
        accessManagerTitle: "Selecione os subgrupos abaixo",
        accessManagerEmptyText: "Nenhum subgrupo atribuido.",
        accessManagerNotFoundText: "Nenhum subgrupo encontrado.",
        accessManagerRemoveTitle: "Remover subgrupo atribuido",
      },
      { name: "expires_at", label: "Expira em", type: "date", optional: true },
    ],
  },
};

export const resourceDefinitions = Object.fromEntries(
  Object.entries(baseResourceDefinitions).map(([key, definition]) => [
    key,
    {
      ...definition,
      columns: definition.columns ? orderDefinitionEntries(definition.columns, "key") : definition.columns,
      fields: definition.fields ? orderDefinitionEntries(definition.fields, "name") : definition.fields,
    },
  ]),
);
