export const BRAZILIAN_STATES = [
  { id: "AC", sigla: "AC", nome: "Acre" },
  { id: "AL", sigla: "AL", nome: "Alagoas" },
  { id: "AP", sigla: "AP", nome: "Amapa" },
  { id: "AM", sigla: "AM", nome: "Amazonas" },
  { id: "BA", sigla: "BA", nome: "Bahia" },
  { id: "CE", sigla: "CE", nome: "Ceara" },
  { id: "DF", sigla: "DF", nome: "Distrito Federal" },
  { id: "ES", sigla: "ES", nome: "Espirito Santo" },
  { id: "GO", sigla: "GO", nome: "Goias" },
  { id: "MA", sigla: "MA", nome: "Maranhao" },
  { id: "MT", sigla: "MT", nome: "Mato Grosso" },
  { id: "MS", sigla: "MS", nome: "Mato Grosso do Sul" },
  { id: "MG", sigla: "MG", nome: "Minas Gerais" },
  { id: "PA", sigla: "PA", nome: "Para" },
  { id: "PB", sigla: "PB", nome: "Paraiba" },
  { id: "PR", sigla: "PR", nome: "Parana" },
  { id: "PE", sigla: "PE", nome: "Pernambuco" },
  { id: "PI", sigla: "PI", nome: "Piaui" },
  { id: "RJ", sigla: "RJ", nome: "Rio de Janeiro" },
  { id: "RN", sigla: "RN", nome: "Rio Grande do Norte" },
  { id: "RS", sigla: "RS", nome: "Rio Grande do Sul" },
  { id: "RO", sigla: "RO", nome: "Rondonia" },
  { id: "RR", sigla: "RR", nome: "Roraima" },
  { id: "SC", sigla: "SC", nome: "Santa Catarina" },
  { id: "SP", sigla: "SP", nome: "Sao Paulo" },
  { id: "SE", sigla: "SE", nome: "Sergipe" },
  { id: "TO", sigla: "TO", nome: "Tocantins" },
];
